### ISSUE TITLE
[WIREFRAME] : 🧷 와이어프레임 만들기

### ISSUE THREAD

**Issue by r6hex-1g** [r6hex-1g/Journet#5]
[해당 피그마 파일에서 와이어프레임도 볼 수 있음](https://www.figma.com/file/v07BG8DRuI9AVYI7DoLTOk/Project%3A-Journet--%3E-DesignBoard?type=design&node-id=0%3A1&mode=design&t=GILIEAQ9IgehsFUe-1)

**Comment by r6hex-1g** [comment]
반응형 와이어프레임 디자인이 필요하고, 그 디자인이 반응성이 높아야 함

**Comment by RunaUXLabs** [comment]
채연이 우선 pc화면 기준으로 퍼블리싱 해주세요! 반응형도 생각해 가면서 쫀득하게 잡아보죠
